version: '3'

services:
  laravel:
    image: lucianodiisouza/laravel:prod
    container_name: laravel
    networks: 
      - laranet

  nginx:
    image: lucianodiisouza/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - 8080:80

networks:
  laranet:
    driver: bridge